apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/NVIDIA/k8s-device-plugin.git
    targetRevision: main 
    path: deployments/helm/nvidia-device-plugin
    helm:
      releaseName: nvidia-device-plugin

      values: |
        # Рекомендуется ограничить установку на GPU-ноды (пример — через label)
        nodeSelector:
          nvidia.com/gpu.present: "true"

        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true